services:
  viaje:
    image: posgres:17.0
    container_name: db_viajando
    environment:
      - POSTGRESS_USER = Facu
      - POSTGRESS_PASSWORD = 1234
      - POSTGRESS_DB = viajando
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data